[package]
name = "exercism"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unicode-segmentation = "1.7.1"
time = {version = "0.3.5",features = ["macros"]}
crossbeam = {version = "0.8.1"}

